version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:7000
    volumes:
      - .:/code
    ports:
      - "7000:7000"
    depends_on:
      - selenium


  selenium:
    image: selenium/standalone-chrome
    ports:
     - 4444:4444
    restart: always 

  

